### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by chocoearly44**
I started creating potion.wiki. I hope it will help players with potions.

### CODE REVIEW

**Comment by EB57PzUhYmQsMm** [comment]
I would like to have that website! I suck at potions and other websites don't give enough info

**Comment by chocoearly44** [comment]
I also want to make forge.web so player can share their own command.

**Comment by WeirdTreeThing** [comment]
I don't know about the potions one because once the official wiki gets updated it might have a potion part in it.

**Comment by WeirdTreeThing** [comment]
And also why just potions why not crafting and smelting?

**Comment by chocoearly44** [comment]
I want to add seperate wiki for that but MrCray didn't respond to my emails.

**Comment by chocoearly44** [comment]
He didn't add potions.wiki to GitWeb.

**Comment by OstenTV** [comment]
You should remove the file extension (.html), and just name it "index"

**Comment by chocoearly44** [comment]
ok

**Comment by chocoearly44** [comment]
closing pull request adn creating new

**Pull request closed without merging**
