### PR TITLE
All Device Mod Recipes added! (howto.craft) !OLD FORMAT DO NOT MERGE!

### PR DESCRIPTION
**Pull request by dhtdht020**
Added all device mod recipes. It's was so hard to add them ;|
The recipes are crazy. Also changed to lighter colors.
image

### CODE REVIEW

**Comment by Pugduddly** [comment]
You probably want to update howto.craft to the new format. I've updated all the sites except it.

**Comment by MinecraftDoodler** [comment]
Conflicting Files

**Comment by dhtdht020** [comment]
Updating to new format
Calm down

**Comment by dhtdht020** [comment]
deleted the old usefulsites file
made conflicts

**Pull request closed without merging**
