### PR TITLE
Converted to new format (howto.craft)

### PR DESCRIPTION
**Pull request by dhtdht020**

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Tip: Put all deletion into one commit instead of individual commits. May as well commit every character change at this point.

**Comment by dhtdht020** [comment]
Commiting every single character change seems like a great idea

**Comment by MrCrayfish** [comment]
I'm serious though, bad practice to commit create individual commits for deletion and additions.
Should have been
**Deleted Minecraft recipes**
**Added Device Mod recipes**

**Comment by dhtdht020** [comment]
I'm not purposely annoying, doing so in the web interface is impossible without some sort of a secondary branch which takes time. I will switch to git though.
I'm very sorry.

**Comment by MrCrayfish** [comment]
I don't recommend using GitHub in the web interface unless it's for very small changes, not bulk tasks.

**Pull request merged**
