### PR TITLE
Create potion.wiki

### PR DESCRIPTION
**Pull request by chocoearly44**
Please I created a bit of it. I just need a folder to put everything in it.
Here is my files repository:
https://github.com/jurijtsl/JurijTSL-GitWeb/tree/master/potion.wiki

### CODE REVIEW

**Comment by WeirdTreeThing** [comment]
You should put the images in the root of the website and put the banner in there and the folder name is setup incorrectly

**Comment by WeirdTreeThing** [comment]
Here try this: https://github.com/WeirdTreeThing/JurijTSL-GitWeb/tree/WeirdTreeThing-patch-1
You still have to update the links to work if it gets merged

**Comment by chocoearly44** [comment]
I let you fix it.

**Comment by chocoearly44** [comment]
Thanks

**Pull request closed without merging**
