### PR TITLE
Create index for GitWeb insite of 'the great wiki'

### PR DESCRIPTION
**Pull request by GwnQuentin**
this is the gitweb pege for 'the great wiki'

### CODE REVIEW

**Comment by OstenTV** [comment]
Completely broken. I would recommend testing it out in GitWeb Builder before you try publishing it.

**Comment by GwnQuentin** [comment]
I cant get gitweb builder to work...

**Comment by jacksonhardaway** [comment]
E.Z. Steps:
1. Get the latest / recommended 1.12.2 version of forge
2. Get the Device Mod 0.4.0
3. Get GitWeb Builder
4. Start your game and make sites.

**Comment by GwnQuentin** [comment]
Were can i find gitweb builder?

**Comment by OstenTV** [comment]
Here https://minecraft.curseforge.com/projects/gitweb-builder

**Pull request closed without merging**
